# NUMPY

- ##### Library For Scientific Computing
- ##### Provide mathematical operations which support Arrays and Matrices


In [1]:
import numpy as np

# Create 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.shape)  # (5,)

## Create 2D Array From 1D Array using reshape
arr2 = np.array([1, 2, 3, 4, 5, 6])
arr2 = arr2.reshape(3, 2)
print(arr2)  # [[1 2],[3 4],[5 6]]

# .arange()
np.arange(0, 10, 2).reshape(5, 1)  # array([[0],[2],[4],[6],[8]])

# .ones()
allOne = np.ones((3, 3))  # [[1. 1. 1.] [1. 1. 1.] [1. 1. 1.]]
print("\n", allOne)

# .eye()
idMat = np.eye(3)  #  [[1. 0. 0.], [0. 1. 0.], [0. 0. 1.]]
print("\n", idMat)

(5,)
[[1 2]
 [3 4]
 [5 6]]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape: ", arr.shape)
print("Number Of Dimensions: ", arr.ndim)
print("Size (No. Of Elements): ", arr.size)
print("Data Type: ", arr.dtype)
print("Item Size (in Bytes): ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number Of Dimensions:  2
Size (No. Of Elements):  6
Data Type:  int64
Item Size (in Bytes):  8


# Numpy Vectorized Operations

## Basic Operations [Universal Operations]


In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Addtition
print("Addition: ", arr1 + arr2)

# Subtraction
print("Subtraction: ", arr1 - arr2)

# multiply
print("Multiply: ", arr1 * arr2)

# Division
print("Division: ", arr1 / arr2)

# Square Root
print("Square Root: ", np.sqrt(arr1))

# Sin
print("Sine: ", np.sin(arr1))

# Natural Log
print("Natural Log: ", np.log(arr1))

# Exponential
print("Exponential: ", np.exp(arr1))

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiply:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]
Square Root:  [1.         1.41421356 1.73205081 2.         2.23606798]
Sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Natural Log:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


## Array Slicing and Accessing


In [4]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array: ", arr)

print("1 row 3rd index: ", arr[0][3])

print("Accesselements (7,8,11,12) :- \n", arr[1:, 2:])

print("Access elements (3,4,7,8) : \n", arr[0:2, 2:])

arr[0][0] = 100
print("Array After Modify: \n", arr)

Array:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1 row 3rd index:  4
Accesselements (7,8,11,12) :- 
 [[ 7  8]
 [11 12]]
Access elements (3,4,7,8) : 
 [[3 4]
 [7 8]]
Array After Modify: 
 [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


# Practical Application

### Statistical Concept -> NORMALISATION

### normalisedData = (arr - mean) / standardDeviation


In [5]:
# To Have Mean = 0 & Standard Deviation = 1 is Normalization
data = np.array([1, 2, 3, 4, 5])

# Mean
mean = np.mean(data)
print("Mean: ", mean)

# Median
median = np.median(data)
print("Median: ", median)

# Variance
variance = np.var(arr)
print("Variance: ", variance)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

# NORAMLISING the Data
normalised_data = (data - mean) / std_dev
print("Normalized Data: ", normalised_data)

Mean:  3.0
Median:  3.0
Variance:  669.8541666666666
Standard Deviation:  1.4142135623730951
Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


# Logical Operation (V.IMP)


In [6]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(data[(data >= 5) & (data <= 8)])  # Only Print Elements Greater than 5

[5 6 7 8]
